name = "trigger-sqs"
description = "A Spin trigger for Amazon SQS events"
version = { from = "Cargo.toml" }
spin_compatibility = ">=2.2"
license = "Apache-2.0"
package = "../../target/release/trigger-sqs"
