name = "trigger-cron"
description = "A Spin trigger for Cron events"
version = { from = "Cargo.toml" }
spin_compatibility = ">=3.0"
license = "Apache-2.0"
package = "../../target/release/trigger-cron"
